# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

name: $(Date:yyyyMMdd)-$(Build.BuildId)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Test'  # The name of your Azure Container Registry
    repository: 'viertel97/google-service'  # The name of the repository
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest,$(Build.BuildNumber)
  

- task: CmdLine@2
  inputs:
    script: 'docker rmi ghcr.io/viertel97/google-service:latest'
- task: CmdLine@2
  inputs:
    script: 'docker rmi ghcr.io/viertel97/google-service:$(Build.BuildNumber)'