# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Raspi


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: Docker@2
  inputs:
    containerRegistry: 'Test'  # The name of your Azure Container Registry
    repository: 'google-service'  # The name of the repository
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'