apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: google-service
  name: google-service
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
      protocol: TCP
      nodePort: 8100
  type: NodePort
  selector:
    io.kompose.service: google-service